export const DASHBOARD_HISTORY_RUNNING_POLL_MS = 3000;
export const DASHBOARD_HISTORY_PENDING_POLL_MS = 6000;
export const DASHBOARD_HISTORY_HIDDEN_POLL_MS = 15000;

export const AUTO_OPTIMIZE_POLL_MS = 2000;
export const AUTO_OPTIMIZE_MAX_POLLS = 90;
export const EDITOR_STATS_DEBOUNCE_MS = 180;

export const EDITOR_DEFAULT_TARGET_WORDS = 1100;
